### ISSUE TITLE
Wrong predicted spectra for modified peptides

### ISSUE THREAD

**Issue by KaiLiCn** [wilhelm-lab/koina#64]
Hi there,

When I tried the example on the Koina server, I found the return m/z values were wrong for modified peptides. Here is one example from the AlphaPept_ms2_generic model. There is a `[UNIMOD:35]` on the last `M`. However, the return m/z value of  `y1+1` is still `150.05831909179688` without modification mass.

Can you take a look?
![image](https://github.com/wilhelm-lab/koina/assets/29800230/dfa54dca-e3ac-4e80-9067-2a12f8b9d430)

**Comment by progistar** [comment]
I found that the same error occurred on Cys+57.021.

**Comment by LLautenbacher** [comment]
This seems to be solved in the newest version.
